### ISSUE TITLE
[Nhóm#2] Lỗi chức năng trên trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131020545** [MonQAQCTH39/MonQAQCTH39#107]
a. Web Browser: Google Chrome Phiên bản 48.0.2564.116 m
b. Các bước phát hiện lỗi:
i.#1: Vào trang http: http://ctct.ueh.edu.vn/
ii.#2: Chọn vào mục "Tư Liệu", Chọn "Hình Ảnh
![2](https://cloud.githubusercontent.com/assets/16597970/13484902/a462d440-e134-11e5-89ad-ce9dcba39227.PNG)
"
iii.#3 Chọn mục "Hội diễn văn nghệ truyền thống - khối sinh viên - năm 2011"
![6](https://cloud.githubusercontent.com/assets/16597970/13484928/01fd11d8-e135-11e5-8f0f-05b250382bf7.PNG)
![4](https://cloud.githubusercontent.com/assets/16597970/13484933/0568d47e-e135-11e5-9cf2-adc05ddd2ac9.PNG)

c. Kết quả thực tế: hiện ra trang 'Not Found'
d. Kết quả mong muốn: dẫn vào trang chứa hình ảnh về chủ đề Hội diễn văn nghệ truyền thống- năm 2011.

**Comment by 31131020525** [comment]
lỗi này đúng rồi nhưng Sửa lại tên lỗi đi bạn ơi
