### ISSUE TITLE
[Nhóm#1] Lỗi chức năng góp ý trên trang http://ttnnkinhte.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131023036** [MonQAQCTH39/MonQAQCTH39#115]
a. Web Browser: Cốc cốc 53.2.131
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://ttnnkinhte.ueh.edu.vn/
ii. #2: Nhấn vào nút "Góp ý"
c. Kết quả thực tế: hệ thống không thực hiện đúng với chức năng.
d. Kết quả mong đợi:hệ thống thực hiện đúng với chức năng, hộp thoại hoặc mẫu góp ý xuất hiện để người dùng có thể đóng góp suy nghĩ của mình.

**Comment by 31131020525** [comment]
chức năng này vẫn hoạt động mà bạn , hình như dùng ms outlook vẫn góp ý dc

**Comment by 31131020525** [comment]
mình đóng lỗi này nhé
