### ISSUE TITLE
[Nhóm#11] Lỗi hiển thị ngôn ngữ trang lms.ueh.edu.vn

### ISSUE THREAD

**Issue by 31131023374** [MonQAQCTH39/MonQAQCTH39#128]
a. Web browser: Cốc cốc Version 51.2.109
b. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang http://lms.ueh.edu.vn/
ii. #2: Nếu ngôn ngữ hiện tại là tiếng việt thì chuyển sang tiếng anh 
![zalo_screenshot_5_3_2016_2329884](https://cloud.githubusercontent.com/assets/16612578/13548758/4c38abe4-e32a-11e5-89c1-0450ed0aec63.png)

ii. #3: Tìm đến nút Đăng nhập
c. Kết quả thực tế: Nút đăng nhập vẫn hiển thị tiếng việt "Đăng nhập"
d. Kết quả mong đợi: Nút đăng nhập phải được chuyển thành "Log in"
![zalo_screenshot_5_3_2016_2326373](https://cloud.githubusercontent.com/assets/16612578/13548764/84c1644c-e32a-11e5-950d-962fd7be8b6d.png)

**Comment by 31131020502** [comment]
xác nhận lỗi không chuyển nút đăng nhập thành log in

**Comment by 31131020502** [comment]
trùng lặp
