### ISSUE TITLE
[Nhóm#1] Lỗi bị đẩy ra khi đang thi trực tuyến trên trang trắc nghiệm

### ISSUE THREAD

**Issue by 31131023036** [MonQAQCTH39/MonQAQCTH39#13]
a. Web Browser: Cốc cốc 53.2.123
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://tracnghiem.youth.ueh.edu.vn/
ii. #2: Nhập thông tin như MSSV, password
iii. #3: Bấm nút đăng nhập
iv. #4: Lựa chọn danh mục các bài thi đang được tổ chức(Rèn luyện đoàn viên) rồi nhấn nút vào thi.
c. Kết quả thực tế: thời gian thi 900s nhưng khi làm bài chưa hết 900s (khoang 600s) thì hệ thống đóng lại và xuất ra kết quả.
d. Kết quả mong đợi: hệ thống phải kiểm soát thời gian thi đúng như thời gian quy định.

**Comment by 31131020525** [comment]
1. không xảy ra lỗi như bạn báo về khi mình xem lại lịch sử thi bằng Cốc cốc 53.2.123 trên trang http://tracnghiem.youth.ueh.edu.vn/ 
2. chọn sai labels và milestone
