### ISSUE TITLE
[Nhóm#11] Không thực hiện được chức năng tìm kiếm trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131021379** [MonQAQCTH39/MonQAQCTH39#130]
a. Web Browser: Google Chrome 48.0.2564.116 m
b. Các bước để phát hiện lỗi:

i. #1: Vào trang http://online.ueh.edu.vn/

ii. #2: Nhấn vào phần tuyển sinh-tra cứu điểm tuyền sinh

iii. #3: Nhập thông tin - nhấn nút tìm kiếm

![2016-03-05](https://cloud.githubusercontent.com/assets/16623129/13548878/cc75a742-e32c-11e5-9914-9f36c44b8b73.png)

c. Kết quả thực tế: Báo lỗi

![2016-03-05 1](https://cloud.githubusercontent.com/assets/16623129/13548875/bfd532be-e32c-11e5-9e0c-542a85af887b.png)

d. Kết quả mong đợi: Hiển thị điểm tuyền sinh

**Comment by 31131020502** [comment]
Lỗi này đã bị trùng
