### ISSUE TITLE
[Nhóm#3] Không hiển thị thông tin nhân sự quản lí

### ISSUE THREAD

**Issue by 31131023612** [MonQAQCTH39/MonQAQCTH39#140]
a. Web Browser: Cốc cốc 53.2.131
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http:http://ttnnkinhte.ueh.edu.vn/
ii. #2: Rê chuột vào thẻ"nhân sự quản lí" và click chuột vào.
c. Kết quả thực tế: không hiện thông tin chi tiết của "nhân sự quản lí"
![image](https://cloud.githubusercontent.com/assets/16625747/13552757/6212fdca-e3a2-11e5-9a8c-d162f7072447.png)

d. Kết quả mong đợi: Thông tin chi tiết của "nhân sự quản lí''

**Comment by vnlinh112** [comment]
Không có dữ liệu chứ không phải lỗi của hệ thống.
