### ISSUE TITLE
[Nhóm#3] cập nhật thiếu tên thầy cô phụ trách môn học

### ISSUE THREAD

**Issue by 31131023612** [MonQAQCTH39/MonQAQCTH39#145]
a. Web Browser: Cốc cốc 53.2.131
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://online.ueh.edu.vn/
ii. #2: Nhấp " Đăng nhập"
iii. #3. Điền "tên đăng nhập" và " mật mã"
iiii. #4.chọn " ý kiến thảo luận"
c. Kết quả thực tế: thiếu 1 số tên của giảng viên phu trách bộ môn
![image](https://cloud.githubusercontent.com/assets/16625747/13552812/acc64204-e3a3-11e5-97c1-d6411ca8fed5.png)

d. Kết quả mong đợi: hiển thi đầy đủ tên các giảng viên của các môn học.

**Comment by vnlinh112** [comment]
Do trường không muốn công bố tên các GV đó, không phải do lỗi hệ thống nhé bạn.
