### ISSUE TITLE
[Nhóm#1]Lỗi không đáp ứng đủ nhu cầu khi đăng ký học phần trên trang online

### ISSUE THREAD

**Issue by 31131020829** [MonQAQCTH39/MonQAQCTH39#27]
a. Web Browser:  Chrome 48.0.2564.82 m
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://online.ueh.edu.vn/ khi tới ngày đăng ký học phần
ii. #2: Nhấn vào nút đăng ký học phần phía bên phải thanh menu
iii. #3: Nhập thông tin như MSSV, password rồi đăng nhập 
c. Kết quả thực tế: Hệ thống bị chập chờn (khi vào được khi không vào được)để thực hiện đăng ký học phần.
d. Kết quả mong đợi: Hệ thống hoạt động trơn tru như bình thường

**Comment by 31131020525** [comment]
1. sai labels và milestone
2. ko thể xác nhận vì hiện tại ko phải thời gian dkhp
3. Mô tả lỗi 1 cách định tính , không cụ thể, chi tiết
