### ISSUE TITLE
[Nhóm#4] Lỗi không thể truy cập vào link khác từ trang thư viện UEH

### ISSUE THREAD

**Issue by huyenbui12** [MonQAQCTH39/MonQAQCTH39#66]
Web Browser: Chrome 48.0.2564.97 m
i #1 Truy cập web http://lib.ueh.edu.vn/
ii #2 Di chuyển xuống cuối trang web
ii #3 Ấn vào "Thư viện Trường Đại học Kinh Tế Thành phố Hồ Chí Minh" 
Kết quả thực tế: Không truy cập được hộp thư điện tử của thư viện.
![image](https://cloud.githubusercontent.com/assets/16612982/12836219/4a7a004e-cbe9-11e5-9897-f8fb7c898d0e.png)

Kết quả mong đợi: Hiện ra hộp thư điện tử của thư viện.

**Comment by vnlinh112** [comment]
Thực ra đây không phải lỗi mà do bạn phải dùng một mail client như Outlook... thì khi click vào link đó, Outlook sẽ mở ra và tạo một mail mới đến địa chỉ đó.

![image](https://cloud.githubusercontent.com/assets/16601841/13482394/7eec6196-e11f-11e5-9c33-d0cbd1a9a76f.png)
