### ISSUE TITLE
[NHÓM#4]Lỗi Chức Năng "Ghi nhớ lần đăng nhập sau" trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131021080** [MonQAQCTH39/MonQAQCTH39#79]
Web browser: Cốc cốc Phiên bản 53.2.129
b. Các bước để phát hiện lỗi:
i.#1:Truy cập vào trang http://online.ueh.edu.vn/
ii.#2: Click chọn đăng nhập
iii.#3: Click "Ghi nhớ lần đăng nhập sau"
c. Kết quả thực tế: lần sau vào đăng nhập tài khoản không được ghi nhớ
d. Kết quả mong đợi: tài khoản đăng nhập được ghi nhớ

**Comment by vnlinh112** [comment]
Lỗi này Hằng đã đăng rồi nên Linh đóng lại nha Huyền
