### ISSUE TITLE
[NHÓM#4]Lỗi giao diện khung bảng trong trang http://regist.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131021080** [MonQAQCTH39/MonQAQCTH39#80]
Web browser: Cốc cốc Phiên bản 53.2.129
b. Các bước để phát hiện lỗi:
i.#1:Truy cập vào trang http://regist.ueh.edu.vn/
ii.#2: Đăng nhập
iii.#3: Click chọn Chương trình đào tạo
iv.#4: Quan sát 
![224](https://cloud.githubusercontent.com/assets/16612313/13097776/c23dc9b4-d556-11e5-8e79-7d44ab5caa27.png)
c. Kết quả thực tế: thiếu gạch dọc khung bên trái
d. Kết quả mong đợi: khung phải đầy đủ gạch ngang, dọc phân chia các cột, dòng

**Comment by vnlinh112** [comment]
Cái này do style nó là như vậy: mỗi ô chỉ có đường viền bên phải và phía dưới, chứ không phải lỗi nhé bạn.
![image](https://cloud.githubusercontent.com/assets/16601841/13483062/de4b798e-e123-11e5-8475-4943ef0052eb.png)

**Comment by vnlinh112** [comment]
Huyền ơi Linh assign cho Hùng không được nên assign cho Huyền, báo lại cho Hùng giúp Linh nhé!
