### ISSUE TITLE
[NHÓM#4]Lỗi Chức Năng không thể tìm kiếm trên trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131021080** [MonQAQCTH39/MonQAQCTH39#81]
Web browser: Cốc cốc Phiên bản 53.2.129
b. Các bước để phát hiện lỗi:
i.#1:Truy cập vào trang http://online.ueh.edu.vn/
ii.#2: Click chọn Tra Cứu Văn Bằng
iii#3: Nhập Năm tốt nghiệp xong click chọn tìm kiếm
![225](https://cloud.githubusercontent.com/assets/16612313/13098747/e0c5e810-d55d-11e5-952b-0c874fc32825.png)
c. Kết quả thực tế: không tìm kiếm được, cũng không báo là nhập sai hay không có
d. Kết quả mong đợi: tìm kiếm và liệt kê giống như tìm kiếm tên
![226](https://cloud.githubusercontent.com/assets/16612313/13098787/54db4786-d55e-11e5-9823-cb9b209c1cd5.png)
Ngày sinh,Mã số sinh viên,Số hiệu bằng tương tự lỗi

**Comment by vnlinh112** [comment]
Mình đã làm theo các bước của bạn và thấy là trang web này chỉ thiếu thông báo khi không tìm thấy kết quả chứ không bị lỗi chức năng tìm kiếm. Bạn post lỗi khác là không có thông báo khi không tìm thấy kết quả nha. Còn lỗi này mình sẽ close.

**Comment by 31131021080** [comment]
ah, là như thế này. lỗi này là như tìm kiếm theo năm. nếu minh chọn 2014
trở  ngược lại thì đáng lẽ phải liệt kê toàn bộ những người tốt nghiệp năm
2014 ak. Như minh tìm kiếm tên thì lại dc

Vào 13:14 Ngày 19 tháng 02 năm 2016, Vu Ngoc Linh notifications@github.com
đã viết:

**Comment by 31131021080** [comment]
nhầm 2013-2014 chua cập nhật

Vào 11:15 Ngày 20 tháng 02 năm 2016, Hung Laivan laivanhung9a2@gmail.com
đã viết:
