### ISSUE TITLE
[NHÓM#4] LỖI CHỨC NĂNG TRA CỨU ĐIỂM TUYỂN SINH BẰNG TÊN 

### ISSUE THREAD

**Issue by 31131021130** [MonQAQCTH39/MonQAQCTH39#94]
a. Web Browser: Chrome - Phiên bản  48.0.2564.116 
b. Các bước để phát hiện lỗi:
i. #1: Truy cập trang http://online.ueh.edu.vn/ 
ii.#2: Click tab tuyển sinh 
![loia](https://cloud.githubusercontent.com/assets/16592238/13421226/a68a1bb4-dfbf-11e5-9e9e-86e76c5852ca.png)
iii.#3 Click tab tra cứu điểm tuyển sinh 
![loib](https://cloud.githubusercontent.com/assets/16592238/13421247/cece9910-dfbf-11e5-859a-82e3bb26baac.png)
iiii.#4 Nhập tên và năm tuyển sinh vào trường 
![loi1](https://cloud.githubusercontent.com/assets/16592238/13421326/49a4dae6-dfc0-11e5-9996-9138bf144d38.png)
c. Kết quả thực tế: Không hiển thị được thông tin tra cứu 
![loi2](https://cloud.githubusercontent.com/assets/16592238/13421350/7529221c-dfc0-11e5-89cb-c9fb08d1a2a3.png)

d. Kết quả mong đợi: hiển thị được thông tin tra cứu

**Comment by huyenbui12** [comment]
trùng lỗi với Huyền rồi nhe
