### ISSUE TITLE
[Nhóm#1] Lỗi chức năng tra cứu thông tin viên chức trên trang http://ueh.edu.vn/

### ISSUE THREAD

**Issue by 31131023036** [MonQAQCTH39/MonQAQCTH39#98]
a. Web Browser: FireFox 44.0.2
b. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://ueh.edu.vn/
ii. #2: Nhấn vào mục viên chức ueh
iii. #3 Rê chuột bấm vào mục tra cứu thông tin 
c. Kết quả thực tế: không thực hiện đúng chức năng của nó là hiện ra mục cần tra cứu mà xuất hiện chỉ là những dấu xanh xanh trên màn hình
d. Kết quả mong đợi: hiện ra các mục tra cứu như là tiến sĩ, thạc sĩ, giáo sư chẳng hạn để lọc trích ra.

**Comment by 31131020525** [comment]
lỗi này không đúng bạn nhé

**Comment by 31131020525** [comment]
mình close nhé
